extensions:
  ImplicitPrelude: false
  OverloadedStrings: true
cabal-file: project.cabal
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  Console:
    target-type: console
    filename: src/Console.hs
  FooBar:
    filename: src/FooBar.hs
  Web:
    target-type: web
    filename: src/Web.hs
